name: flutter_material_pickers
description: A flutter package for showing material themed picker dialogs. This suite provides a set of new commonly used pickers and wraps some pre-existing ones into a consistent display paradigm.
version: 1.1.0
homepage: https://github.com/codegrue/flutter_material_pickers

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.2.6
  intl: ^0.16.0
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <3.0.0"

flutter:
  uses-material-design: true
